services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: Services/Discount/Discount.Grpc
      dockerfile: Dockerfile

  orderdb:
   image: mcr.microsoft.com/mssql/server
volumes:
  postgres_catalog:
  postgres_basket:
